"""Domain primitive types.

Per the architecture, we use:
- ``NewType`` for IDs so the type checker prevents mixing them up.
- ``TypeAlias`` for value types like Price/Quantity that share a runtime
  representation (Decimal) but carry semantic meaning.

Money is **always** Decimal in this codebase. Floats are forbidden in any
code path that touches prices, quantities, or PnL — they are reserved for
indicators, statistics, and other quantitative computations where the
inexactness is acceptable.
"""

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import NewType, TypeAlias
from uuid import UUID

# --- Identifiers -----------------------------------------------------------
# NewType creates a distinct subtype at type-check time but is just an alias 
# at runtime. Mixing an OrderId with a ClientOrderId is a type error.

OrderId = NewType("OrderId", UUID) 
"""Internal order identifier, generated by the OMS at order creation time."""

ClientOrderId = NewType("ClientOrderId", str)
"""Idempotency key sent to the exchange. Used to dedupe retries."""

ExchangeOrderId = NewType("ExchangeOrderId", str)
"""Order id assigned by the exchange after acknowledgement."""

StrategyId = NewType("StrategyId", str)
"""Stable identifier for a registered strategy instance."""

FillId = NewType("FillId", UUID)
"""Internal fill id; one fill event per partial or complete execution."""

EventId = NewType("EventId", UUID)
"""Globally-unique event id; appears on every BaseEvent."""

# --- Value types -----------------------------------------------------------
# Decimal everywhere money flows. Precision is preserved through serialization
# via Pydantic's Decimal handling (configured in events.py).
# With TypeAlias, the type checker sees Price and Decimal as the same type

Price: TypeAlias = Decimal
"""A price quoted in the instrument's quote currency."""

Quantity: TypeAlias = Decimal
"""A quantity expressed in the instrument's base unit (or contracts)."""

Notional: TypeAlias = Decimal
"""Price * Quantity, in quote currency. Used for risk calculations."""

Symbol: TypeAlias = str
"""Exchange-specific instrument symbol, e.g. "BTC-USDT", "ESZ4". """

# Nanoseconds since Unix epoch. Integer arithmetic is faster and exact;
# ``datetime`` is for display, ``Timestamp`` is for the wire and the bus.
Timestamp: TypeAlias = int


# --- Enumerations ----------------------------------------------------------

# Enum is a way to define a fixed set of named constants

# Use @property when a method:
# 1) Takes no arguments (besides self)
# 2) Returns a value derived from existing state
# 3) Conceptually feels like a fact about the object, not an action

class Side(str, Enum):
    """Buy or sell. ``str`` mixin makes it JSON-friendly."""

    BUY = "BUY"
    SELL = "SELL"

    @property
    def sign(self) -> int:
        """+1 for buys, -1 for sells. Useful for position math."""
        return 1 if self is Side.BUY else -1


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"
    IOC = "IOC"  # Immediate-Or-Cancel
    FOK = "FOK"  # Fill-Or-Kill
    POST_ONLY = "POST_ONLY"  # Maker-only limit order


class TimeInForce(str, Enum):
    GTC = "GTC"  # Good-Till-Cancelled
    IOC = "IOC"
    FOK = "FOK"
    DAY = "DAY"
    GTD = "GTD"  # Good-Till-Date


class OrderStatus(str, Enum):
    """Lifecycle states. Transitions enforced in oms/state_machine.py."""

    PENDING_NEW = "PENDING_NEW"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    PENDING_CANCEL = "PENDING_CANCEL"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"

    @property
    def is_terminal(self) -> bool:
        """Terminal states never transition further."""
        return self in {
            OrderStatus.FILLED,
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.EXPIRED,
        }


class Severity(str, Enum):
    """Severity for risk decisions and alerts."""

    INFO = "INFO"
    WARN = "WARN"
    BLOCK = "BLOCK"  # Reject this signal but keep system running.
    KILL = "KILL"  # Trigger kill switch.


class AssetType(str, Enum):
    SPOT = "SPOT"
    PERPETUAL = "PERPETUAL"
    FUTURE = "FUTURE"
    OPTION = "OPTION"
    EQUITY = "EQUITY"
    FX = "FX"


__all__ = [
    "AssetType",
    "ClientOrderId",
    "EventId",
    "ExchangeOrderId",
    "FillId",
    "Notional",
    "OrderId",
    "OrderStatus",
    "OrderType",
    "Price",
    "Quantity",
    "Severity",
    "Side",
    "StrategyId",
    "Symbol",
    "TimeInForce",
    "Timestamp",
]
